### start process instance
POST http://localhost:8100/process/start
Content-Type: application/json

{
  "runtimeConfig": {
    "bpmnProcessId": "CLMdirectHauptauftragV2",
    "debugSkipCLMK": false
  }
}

### add neukundenanlage
@bpmnProcessId = CLMdirectHauptauftragV2
@processBusinessKey = a1e159b5-f89f-4b69-82ad-b6d0f3edd84b
@processInstanceKey = 2251799814427970

POST http://localhost:8100/process/neukundenanlage
Content-Type: application/json

{
  "kundenName": "Kunde1",
  "messageRuntimeConfig": {
    "messageCorrelationKey": "{{processBusinessKey}}"
  }
}


### add kontoanlage
POST http://localhost:8100/process/kontoanlage
Content-Type: application/json

{
  "kontoName": "Konto3",
  "messageRuntimeConfig": {
    "messageCorrelationKey": "{{processBusinessKey}}"
  }
}


### add uvzanlage
POST http://localhost:8100/process/uvzanlage
Content-Type: application/json

{
  "uvzName": "Uvz3",
  "kontoName": "Konto2",
  "messageRuntimeConfig": {
    "messageCorrelationKey": "{{processBusinessKey}}"
  }
}

### get process instance
GET http://localhost:8100/process/{{processInstanceKey}}

### get process instances
GET http://localhost:8100/process/search?
    bpmnProcessId={{bpmnProcessId}}

### finish process instance
POST http://localhost:8100/process/ausgefuert
Content-Type: application/json

{
  "messageRuntimeConfig": {
    "messageCorrelationKey": "{{processBusinessKey}}"
  }
}